### ISSUE TITLE
.cats file format needs to be documented

### ISSUE THREAD

**Issue by segfaultxavi** [symbol/catbuffer-schemas#13]
As far as I'm aware this format is not documented anywhere. I wouldn't go as far as writing the Backus-Naur form of the syntax but SOME instructions are definitely required.

The best place seems the README in this repo and later on a full article in the [docs site](https://docs.symbolplatform.com/guidelines/generating-transaction-builders.html) or the handbook (just like we have C++ [coding guidelines](https://docs.symbolplatform.com/handbook/en/cpp-coding-guidelines.html)).

**Naming conventions:**
1. Types: UpperCamelCase
2. Variables: snake_case
3. Const and enum values: TITLE_CASE

**Keywords:**
``using`` defines an alias, typically used for fixed size arrays
``struct`` defines a packed data structure
``inline struct`` defines a packed data structure that must be inlined (think of it as a macro)
``enum`` enumeration of constant values

I'll need help figuring out the rest of the structure.

**Comment by Jaguar0625** [comment]
https://github.com/symbol/catbuffer-parser/blob/dev/docs/cats_dsl.md
