### ISSUE TITLE
Cosignature schema issues (Nem schema)

### ISSUE THREAD

**Issue by fboucquez** [symbol/catbuffer-schemas#23]
1. Invalid `multisig_account_address`  should be SizePrefixedAddress rather than SizePrefixedPublicKey https://github.com/symbol/catbuffer-schemas/pull/22

 2. Invalid `SizePrefixedHash256` size (should be 32 rather than 40) https://github.com/symbol/catbuffer-schemas/blob/main/nem/types.cats#L21

3. Missing `hash` object size. 
Similar to object size when in a list, the hash field has an object size (36) missing in the new schema

```java=
final Hash hash = Utils.generateRandomHash();

System.out.println("Standalone");
System.out.println(HexEncoder.getString(BinarySerializer.serializeToBytes(hash)));
/// 20000000 aa5d760529d4e8321a39c89e31bca122e7ec577a00a8b6171b6457a6251e9d1d

try (BinarySerializer binarySerializer = new BinarySerializer()) {
	binarySerializer.writeObject("data",hash);
	System.out.println("object");
	System.out.println(HexEncoder.getString(binarySerializer.getBytes()));
// 24000000 20000000 aa5d760529d4e8321a39c89e31bca122e7ec577a00a8b6171b6457a6251e9d1d
// 2 sizes, 36 and 32
}
````

https://github.com/NemProject/nem.core/blob/dev/src/main/java/org/nem/core/model/MultisigSignatureTransaction.java#L85

Example MultisigSignatureTransaction payload:

```
 (header)
02100000010000987B00000020000000BC3ADCF3A83AC10F2C20F8BB579DD537DC8988B63D68CBE1DC7FE44728ACB3AB40000000511CD2F6DD266AC1C5A3DCDF5B1A52010C234F6DAD99F056A3CE89BF24D28F73EBF6ECC3EDF4FF6861E0D3C1967D0C3B1B55020ADCE89B797702FD0F18B69C9C808D5B0000000000539E0800
(same as always)

(body)
24000000 20000000 20CFA7686B4AEFCF7C1BD11C17B20D20CEFCE7F58FC12F29B09674959158EB39 28000000 54424D56574A33333558554A5732443646555A575951434C58433335574C56375150554632514741
```

| Name | Size | Hex Value | Parsed Value | Remark  |
| - | - | - | - | - |
| multisigTransactionHashObjectSize | 4 | 24000000 | 36 | Missing in new NEM schemas (bug n3) |
| multisigTransactionHashSize | 4 | 20000000 | 32  | Ok |
| multisigTransactionHash | 32 | 20CFA7686B4AEFCF7C1BD11C17B20D20CEFCE7F58FC12F29B09674959158EB39 | same | Wrong size in the schema (bug n2) |
| multisigAccountAddressSize | 4 | 28000000 | 40 | ok |
| multisigAccountAddress | 40 | 54424D56574A33333558554A5732443646555A575951434C58433335574C56375150554632514741 | same | Wrong size in the schema (bug n1) |

**Possible fix for 2 and 3:**

````
# binary layout for a size prefixed 32-byte hash
inline struct SizePrefixedHash256

        # the size of the hash object
	object_size = make_reserved(uint32, 36)  <- add something like this but this doesn't work on a stand-alone HashBuilder

	# hash size
	size = make_reserved(uint32, 32)  <- Change from 40 to 32

	# hash value
	__value__ = Hash256
````

Should we change the name of `SizePrefixedHash256` for Hash256Object or similar?

**Comment by Jaguar0625** [comment]
Fixed in 6685e0f and 4aa60b9.
