### ISSUE TITLE
MultisigAccountModification issues (Nem Schema)

### ISSUE THREAD

**Issue by fboucquez** [symbol/catbuffer-schemas#26]
1. missing size of min_approval_delta object
https://github.com/symbol/catbuffer-schemas/pull/25

2. missing outer MultisigAccountModification size (between list and object)

This issue is similar to https://github.com/symbol/catbuffer-schemas/issues/21#issuecomment-927844306

Example MultisigAccountModification payload:

```
 (header)
01100000020000987B00000020000000CE90BF88FF613587DD38497AD3ECC563A8BE181DF0CA840C74A192E558586002400000008FEDEF8D30372EBBA5AC076CC285BF55130680FAC849EB8C485EB1CEB6D456AE9C8913222126B2F9EC3DC13129230A1297EA0C0D665FE0F52FC71E6093A5CF1880B14F0100000000539E0800
(same as always)

(body)
01000000 28000000 02000000 20000000 ca69aa4dd32abe25d226224740be2a7240672dcc62c177e75a945bd2cfe6aa10 04000000 01000000
```

| Name | Size | Hex Value | Parsed Value | Remark  |
| - | - | - | - | - |
| modificationsCount | 4 | 01000000 | 1 | OK |
| multisigModificationSize | 4 | 28000000 | 40  | Missing (bug 2) |
| modificationType | 4 | 02000000 | 2 | OK |
| cosignatoryPublicKeySize | 4 | 20000000 | 32 | OK |
| cosignatoryPublicKey | 32 | CA69AA4DD32ABE25D226224740B E2A7240672DCC62C177E75A945BD2CFE6AA10 | same | OK |
| minApprovalDeltaSize | 4 | 04000000 | 4 | Not in schema (bug n1) |
| minApprovalDelta | 4 | 01000000 | 1 |  OK|

**Comment by Jaguar0625** [comment]
fixed by #49
