### ISSUE TITLE
MosaicDefinition issues (nem schema)

### ISSUE THREAD

**Issue by fboucquez** [symbol/catbuffer-schemas#28]
I'm testing MosaicDefinitionTransactions, but before getting into the details of the transaction, I think it's better to dig into the MosaicDefinition schema. 

Payload without levy:

`20000000eca0b9c3498a9266292e6bc767110a02e479d215afa1c0b79c86cd5e1f3b5eb8260000000e000000616c6963652e766f75636865727310000000616c696365277320766f7563686572731100000070726563696f757320766f75636865727304000000150000000c00000064697669736962696c6974790100000033160000000d000000696e697469616c537570706c7901000000301a0000000d000000737570706c794d757461626c650500000066616c7365180000000c0000007472616e7366657261626c65040000007472756500000000`

| Name | Size | Hex Value | Parsed Value | Remark  |
| - | - | - | - | - |
| ownerPublicKeySize | 4 | 20000000 | 32 | OK |
| ownerPublicKey | 32 | eca0b9c3498a9266292e 6bc767110a02e4 79d215afa1c0b79c86cd5e1f3b5eb8 | same | OK |
| mosaic id object size | 4 | 26000000 | 38 | **Missing https://github.com/symbol/catbuffer-schemas/issues/21** |
| namespaceIdSize | 4 | 0e000000 | 14 | OK |
| namespaceId | 14 | 616c6963652e766f756368657273 | OK |
| nameSize | 4 | 10000000 | 16 | OK |
| name | 16 | 616c696365277320766f756368657273 | same | OK |
| descriptorSize | 4 | 11000000 | 17 | OK |
| description | 17 | 70726563696f757320766f756368657273 | same | OK |
| propertiesLenght | 4 | 04000000 | 4 | OK
| propertyObjectSize | 4 | 15000000 | 21 | Missing |
| nameSize | 4 | 0c000000 | 12 | OK
| name | 12 64697669736962696c697479 | same | OK|
| valueSize | 4 | 01000000 | 1 | OK |
| value | 1 | 33 | same | OK |
| propertyObjectSize | 4 | 16000000 | 22 | **Missing Bug n1** |
| nameSize | 4 | 0d000000 | 13 | OK
| name | 13 696e697469616c537570706c79 | same | OK|
| valueSize | 4 | 01000000 | 1 | OK |
| value | 1 | 30 | same | OK |
| propertyObjectSize | 4 | 1a000000 | 26 | **Missing Bug n1** |
| nameSize | 4 | 0d000000 | 13 | OK
| name | 13 737570706c794d757461626c65 | same | OK|
| valueSize | 4 | 05000000 | 5 | OK |
| value | 4 | 66616c7365 | same | OK |
| propertyObjectSize | 4 | 18000000 | 24 | **Missing Bug n1** |
| nameSize | 4 | 0c000000 | 12 | OK
| name | 12 7472616e7366657261626c65 | same | OK|
| valueSize | 4 | 04000000 | 4 | OK |
| value | 4 | 74727565 | same | OK |
| levyObjectSize | 4 | 00000000 | 0 | **Bug n2, it's not FFFFFFFF** |

(When a levy is present, the levy object seems ok.)

Bugs:

1. Missing outer object size in MosaicProperty

2. When Levy object is not present, the serialized value is 00000000 and not the FFFFFFFF sentinel. PR https://github.com/symbol/catbuffer-schemas/pull/27

The null object is serialized as empty binary []
https://github.com/NemProject/nem.core/blob/dev/src/main/java/org/nem/core/serialization/BinarySerializer.java#L109

So the size 0 is serialized, not FFFFFFFF (array is empty, not null)
https://github.com/NemProject/nem.core/blob/dev/src/main/java/org/nem/core/serialization/BinarySerializer.java#L91

https://github.com/symbol/catbuffer-schemas/blob/main/nem/mosaic/mosaic_definition.cats#L68

levy_size field should also be calculated some how, not provided by the user.

**Comment by Jaguar0625** [comment]
fixed by #49
