### ISSUE TITLE
MosaicDefinitionTransaction issue (Nem Shema)

### ISSUE THREAD

**Issue by fboucquez** [symbol/catbuffer-schemas#29]
Payload:

````
(header)
01400000010000987b00000020000000c5a8dc55ab416c0294bd83ad2e54130c89e329c9e7d84971886473189bf8c15c4000000077d53110ee3fbbf06859e7808b67bd06ceb97a73237695c588264186070dd567859de64d8c2715725f2b2a1dde9b95e39af425639c6c66245a97193bf982f0e700f36f0600000000539e0800

(Body)
dd00000020000000c5a8dc55ab416c0294bd83ad2e54130c89e329c9e7d84971886473189bf8c15c2b0000000e000000616c6963652e766f75636865727315000000616c6963652773206769667420766f7563686572731100000070726563696f757320766f75636865727304000000150000000c00000064697669736962696c6974790100000033160000000d000000696e697469616c537570706c7901000000301a0000000d000000737570706c794d757461626c650500000066616c7365180000000c0000007472616e7366657261626c6504000000747275650000000028000000544233575158344f32585558564d4d4b4f3648544734584c435a374f593546545546494c43523555c0d4540700000000
````

| Name | Size | Hex Value | Parsed Value | Remark  |
| - | - | - | - | - |
| mosaicDefinitionSize | 4 | dd000000 | 221 | **Missing (Bug 1)** |
| mosaicDefinition | 221 | 20000000c5a8dc55ab416c02 ..... 72756500000000 | object |  see https://github.com/symbol/catbuffer-schemas/issues/28 |
| rentalFeeSinkSize | 4| 28000000 | 40 | OK |
| rentalFeeSink | 40 | 544233575158344f32585558564d4 d4b4f3648544734584c435 a374f593546545546494c43523555 | same | OK |
| rentalFee | 8 | c0d4540700000000 | 123000000 | OK | 

1. Missing mosaic definition outer size between the transaction and the definition field. Note this value is dynamic.

**Comment by Jaguar0625** [comment]
fixed by #49
