### ISSUE TITLE
entityType and type name mismatch

### ISSUE THREAD

**Issue by fboucquez** [symbol/catbuffer-schemas#3]
Currently, there is a mismatch between the name of the constant `entityType` with the actual `type` field in the inline 'Transaction/EntityBody' 

```
struct TransferTransaction
	const uint8 version = 1
	const EntityType entityType = 0x4154 <- "entityType"

	inline Transaction
	inline TransferTransactionBody
```
https://github.com/symbol/catbuffer-schemas/blob/main/schemas/transfer/transfer.cats#L29

````
struct EntityBody
.....

	# entity version
	version = uint8
.....
	# entity type
	type = EntityType <- "type"
````

https://github.com/symbol/catbuffer-schemas/blob/main/schemas/entity.cats#L56

It's harder for the generator to detect that the const refers to the same field (in a generic way).  Note how `version` nicely matches the name between the const and the field.

Is it possible to replace the schemas to?:
````
struct TransferTransaction
	const uint8 version = 1
        const EntityType type = 0x4154 <- "type"
````

**Comment by gimer** [comment]
The mistmatch is intentional:
 * there's a CONST named entityType (or `Entity_Type`,  or whatever language requires), that const is always set to proper value
 * then there's a FIELD callled `type` that is set to given transaction type (so i.e. TransferTransaction.entityType)
 * I assume you don't have _both_ fields in JS, but that's not the case in other generators
 
 technically, once types are generated, there's nothing that should stop you from doing something like:
 `tx.type = TransferTransaction.Entity_Type`
 
the `version` const should actually be called `Current_Version` (in case of catbuffer, there probably will be different versions of the struct...)

**Comment by fboucquez** [comment]
Ok, the issue is how can we map that a const "Current_Version" or  "entityType" is related to the version or type field in the schema, at schema level. Maybe naming convention?  version => const_version, type=>const_type? if not they seem unrelated and the generator needs to handle it.

Related:

https://github.com/symbol/catbuffer-generators/pull/162

**Comment by gimer** [comment]
yeah, imo only _naming convention_ makes sense (that is: it doesn't make sense to extend `catbuffer-parser` even more)

for type: `Entity_Type` is the only one that makes sense
for version: technically we could go with `Entity_Version`, but I don't like it very much, here's why:

`Entity_Type` is what defines entity (and it tied to entity), and `Entity_Version` isn't really tied to entity class, but to given _version_ of entity class.

cc: @Jaguar0625

**Comment by fboucquez** [comment]
The way I see it, the version (or versions) constants are related to the version field of the object. The generator should only allow that/those value/s by just initializing it by default, only allowing those values (compile-time) or by doing assertions (runtime)

Example (one version):
```
truct TransferTransaction
	const uint8 ENTITY_VERSION = 1
	const EntityType ENTITY_TYPE = 0x4154 

	inline Transaction
	inline TransferTransactionBody
```

Would generate:

```
export class  TransferTransactionBuilder extends TransactionBuilder implements Serializer {
    public static readonly ENTITY_VERSION = 1;
    public static readonly ENTITY_TYPE = EntityTypeDto.TRANSFER_TRANSACTION;
    
    public static createTransferTransactionBuilder(
        signature: SignatureDto,
        signerPublicKey: KeyDto,
        network: NetworkTypeDto,
        fee: AmountDto,
        deadline: TimestampDto,
        recipientAddress: UnresolvedAddressDto,
        mosaics: UnresolvedMosaicBuilder[],
        message: Uint8Array,
    ): TransferTransactionBuilder {
        const version = TransferTransactionBuilder.ENTITY_VERSION;
        const type = TransferTransactionBuilder.ENTITY_TYPE;
        return new TransferTransactionBuilder({
            signature: signature,
            signerPublicKey: signerPublicKey,
            version: version,
            network: network,
            type: type,
            fee: fee,
            deadline: deadline,
            recipientAddress: recipientAddress,
            mosaics: mosaics,
            message: message,
        });
    }
```    
If we add a new constant (2 versions for the same schema),

```
struct TransferTransaction
	const uint8 ENTITY_VERSION_1 = 1
	const uint8 ENTITY_VERSION_2 = 2
	const EntityType ENTITY_TYPE = 0x4154 

	inline Transaction
	inline TransferTransactionBody
```
Generated code would be:

```

export class  TransferTransactionBuilder extends TransactionBuilder implements Serializer {
    public static readonly ENTITY_VERSION_1 = 1;
     public static readonly ENTITY_VERSION_2 = 2;
    public static readonly ENTITY_TYPE = EntityTypeDto.TRANSFER_TRANSACTION;
    
    public static createTransferTransactionBuilder(
        version: [TransferTransactionBuilder.ENTITY_VERSION_1,  TransferTransactionBuilder.ENTITY_VERSION_2] <--- allows only those values or adding assertions that reject anything different at runtime.
        signature: SignatureDto,
        signerPublicKey: KeyDto,
        network: NetworkTypeDto,
        fee: AmountDto,
        deadline: TimestampDto,
        recipientAddress: UnresolvedAddressDto,
        mosaics: UnresolvedMosaicBuilder[],
        message: Uint8Array,
    ): TransferTransactionBuilder {
        const version = TransferTransactionBuilder.VERSION;
        return new TransferTransactionBuilder({
            signature: signature,
            signerPublicKey: signerPublicKey,
            version: version,
            network: network,
            type: type,
            fee: fee,
            deadline: deadline,
            recipientAddress: recipientAddress,
            mosaics: mosaics,
            message: message,
        });
    }
````
Having said that, I think the use case of the version is to allow different schemas for the same transaction/state type, like adding/remove/updating a field (one example was the VotingKetLinkV2). 

So the new schema would be (a second schema with one version):
    
```
truct TransferTransactionV2
	const uint8 ENTITY_VERSION = 2
	const EntityType ENTITY_TYPE = 0x4154 

	inline Transaction
	inline TransferTransactionBodyV2 <--- new fields into the body.
```   

That actually generates a new Builder object, the user would need to select the right builder according to the fork height.
In my mind, the "ID" of a state/schema is the EntityType+Version. 

The new TransferTransactionV2Builder would be like the TransferTransactionBuilder but with other fields and version.
```
export class  TransferTransactionV2Builder extends TransactionBuilder implements Serializer {
    public static readonly ENTITY_VERSION = 2;
    public static readonly ENTITY_TYPE = EntityTypeDto.TRANSFER_TRANSACTION;
    
    public static createTransferTransactionBuilderV2(
        signature: SignatureDto,
        signerPublicKey: KeyDto,
        network: NetworkTypeDto,
        fee: AmountDto,
        deadline: TimestampDto,
     
        .... V2 properties
        recipientAddress: UnresolvedAddressDto,
        mosaics: UnresolvedMosaicBuilder[],
        message: Uint8Array,
    ): TransferTransactionV2Builder {
//THEY ARE CONSTANTS
        const version = TransferTransactionBuilder.ENTITY_VERSION;
        const type = TransferTransactionBuilder.ENTITY_TYPE;
        return new TransferTransactionBuilder({
            signature: signature,
            signerPublicKey: signerPublicKey,
            version: version,
            network: network,
            type: type,
            fee: fee,
            deadline: deadline,
             .... V2 properties
            recipientAddress: recipientAddress,
            mosaics: mosaics,
            message: message,
        });
    }
```   

I hope it makes sense. It would be great if the contants/s can be related to a field so we can create better builders. Naming conventions can do the trick.

Related to https://github.com/symbol/catbuffer-generators/pull/162

**Comment by gimer** [comment]
(I let myself to edit your comment to hide generated code)

yes, in case of different version, catbuffer will have separate struct (like V2 in your example)

**Comment by Jaguar0625** [comment]
This has been improved as part of the V2 schema updates.

The code in question looks like this now:
```
struct TransferTransaction
	version = make_const(uint8, 1)
	transaction_type = make_const(TransactionType, transfer)
```
