### ISSUE TITLE
MultisigTransaction issues (Nem Schema)

### ISSUE THREAD

**Issue by fboucquez** [symbol/catbuffer-schemas#31]
1. Invalid transaction type (0x1004 rather than 0x1003) https://github.com/symbol/catbuffer-schemas/pull/30

2. otherTransaction includes non-verifiable fields like the signature

nem.core:
https://github.com/NemProject/nem.core/blob/dev/src/main/java/org/nem/core/model/MultisigTransaction.java#L149

nem schema:
https://github.com/symbol/catbuffer-schemas/blob/main/nem/multisig/multisig.cats#L34 (nothing about excluding non verifiable fields like signature)

## Question

Is it possible to flag verifiable/nonverifiable fields in the schema? It would be nice if the serialize method has a includeNonVerifiableData flag. This could be useful for:

1 - Documentation, to know if a field is (or is not) a part of the signing body or the transaction hash.
2 - For SDK/App to easily get the body of a transaction to be signed or hashed. 
3 - For nem's multisg transaction when serializing/parsing `otherTransactions`

**Comment by Jaguar0625** [comment]
fixed by #49
