### ISSUE TITLE
resolution statements are wrong

### ISSUE THREAD

**Issue by gimre-xymcity** [symbol/catbuffer-schemas#38]
right now both `MosaicResolutionStatement` and `AddressResolutionStatement` inline Receipt.

It just so happens that `Receipt` itself inlines `SizePrefixedEntity`.

Although `Receipt` is indeed `SizePrefixedEntity`, it also happens that right now those two resolution statements do not correspond to any structures within symbol client (aka catapult.server).

**Comment by Jaguar0625** [comment]
fixed by #50
